import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar/Navbar";  // Updated Navbar import
import { Toaster } from "@/components/ui/toaster";
import Sidebar from "@/components/sidebar/Sidebar"; // You can uncomment when Sidebar is needed

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pranav Gandesree ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="absolute top-0 z-[-2] h-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            <Navbar /> 
            {/* <Sidebar /> */}

          <div className="mt-24">
          {children}
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
